services:

  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
    ports:
      - 5432:5432